import { expect, test } from '@playwright/test'

test('neuron, graded mastery, bookmarks, and theme persist', async ({ page }) => {
  await page.goto('./#/lesson/neuron')
  await page.getByRole('tab', { name: 'Experiment', exact: true }).click()
  await expect(page.getByTestId('weighted-sum')).toHaveText('0.42')
  await page.getByLabel('Bias', { exact: true }).fill('0.6')
  await expect(page.getByTestId('weighted-sum')).toHaveText('0.92')
  await page.getByRole('button', { name: 'Bookmark lesson', exact: true }).click()
  await page.getByRole('button', { name: 'Switch to dark mode' }).click()
  await page.getByRole('tab', { name: 'Quiz & challenge' }).click()
  await page.getByRole('button', { name: 'B It increases by 0.5' }).click()
  await page.getByRole('button', { name: 'Check answer', exact: true }).click()
  await page.getByLabel('Challenge answer').fill('0.3')
  await page.getByRole('button', { name: 'Check result' }).click()
  await page.reload()
  await expect(page.locator('.lesson-meta .mastery-badge')).toHaveText('Mastered')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('button', { name: 'Remove bookmark' })).toBeVisible()
})

test('code execution is real, handles errors, and times out loops', async ({ page }) => {
  await page.goto('./#/lesson/neuron')
  await page.getByRole('tab', { name: 'Code lab', exact: true }).click()
  await page.getByRole('button', { name: 'Run code', exact: true }).click()
  await expect(page.locator('.code-output pre')).toContainText('0.603483')
  await page.getByLabel('JavaScript code editor').fill('console.log(6 * 7)')
  await page.getByRole('button', { name: 'Run code', exact: true }).click()
  await expect(page.locator('.code-output pre')).toHaveText('42')
  await page.getByLabel('JavaScript code editor').fill('throw new Error("test error")')
  await page.getByRole('button', { name: 'Run code', exact: true }).click()
  await expect(page.locator('.code-output pre')).toContainText('test error')
  await page.getByLabel('JavaScript code editor').fill('while (true) {}')
  await page.getByRole('button', { name: 'Run code', exact: true }).click()
  await expect(page.locator('.code-output pre')).toContainText('exceeded 2 seconds')
})

test('attention masking and source retrieval expose actual calculations', async ({ page }) => {
  await page.goto('./#/lesson/attention')
  await page.getByRole('tab', { name: 'Experiment', exact: true }).click()
  await expect(page.locator('.attention-grid button').filter({ hasText: 'masked' })).toHaveCount(3)
  await page.getByLabel('Causal mask').uncheck()
  await expect(page.locator('.attention-grid button').filter({ hasText: 'masked' })).toHaveCount(0)
  await page.goto('./#/lesson/rag')
  await page.getByRole('tab', { name: 'Experiment', exact: true }).click()
  await page.getByRole('button', { name: 'Retrieve', exact: true }).click()
  await expect(page.locator('.retrieval-results>div').first()).toContainText('Attention compares queries')
})

test('TensorFlow trains the XOR network and renders a decision boundary', async ({ page }) => {
  await page.goto('./#/lesson/training')
  await page.getByRole('tab', { name: 'Experiment', exact: true }).click()
  await page.getByRole('button', { name: 'Train 100 epochs', exact: true }).click()
  await expect(page.locator('.training-lab .result-pair')).toContainText('Epoch100', { timeout: 50000 })
  await expect(page.locator('.decision-boundary rect')).toHaveCount(901)
  await expect(page.locator('.training-lab .result-pair')).toContainText('100%')
  await expect(page.locator('.error-message')).toHaveCount(0)
})

test('search, glossary, knowledge map, and token trace navigate', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /Search anything/ }).click()
  await page.getByRole('textbox', { name: 'Search curriculum' }).fill('KV cache:')
  await page.locator('.search-results button').first().click()
  await expect(page).toHaveURL(/lesson\/cache/)
  await page.goto('./#/glossary')
  await page.getByLabel('Search glossary').fill('LoRA')
  const lora = page.locator('.glossary-list>a').filter({ has: page.getByRole('heading', { name: 'LoRA', exact: true }) })
  await expect(lora).toHaveCount(1)
  await lora.click()
  await expect(page).toHaveURL(/lesson\/compression/)
  await page.goto('./#/map')
  await expect(page.locator('.map-stage')).toHaveCount(16)
  await page.goto('./#/trace')
  await page.getByRole('button', { name: 'Next operation' }).click()
  await expect(page.locator('.trace-step.current')).toContainText('ID = 1')
})

test('every major view fits a mobile viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  for (const route of ['lesson/neuron', 'lesson/attention', 'lesson/convolution', 'lesson/lstm', 'lesson/matrices', 'lesson/training', 'lesson/tokenization', 'lesson/cache', 'labs', 'map', 'glossary', 'trace', 'progress']) {
    await page.goto(`./#/${route}`)
    await page.locator('h1').waitFor()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), route).toBe(true)
  }
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await expect(page.locator('.sidebar')).toHaveClass(/open/)
  await page.getByRole('button', { name: 'Close navigation' }).click()
  await page.goto('./#/lesson/neuron')
  await page.screenshot({ path: 'test-results/mobile-neuron.png', fullPage: true })
})

test('production works offline beneath a GitHub Pages repository path', async ({ page, context }) => {
  await page.goto('./#/lesson/neuron')
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true)
  await context.setOffline(true)
  await page.reload()
  await page.getByRole('tab', { name: 'Experiment', exact: true }).click()
  await expect(page.getByTestId('weighted-sum')).toHaveText('0.42')
  await page.goto('http://127.0.0.1:4175/Astra/#/lesson/attention')
  await page.getByRole('tab', { name: 'Experiment', exact: true }).click()
  await expect(page.locator('.attention-grid button')).toHaveCount(9)
  await page.getByRole('tab', { name: 'Code lab', exact: true }).click()
  await page.getByRole('button', { name: 'Run code', exact: true }).click()
  await expect(page.locator('.code-output pre')).toContainText('scores')
})